# Generated by Django 4.1b1 on 2023-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0004_alter_quiz_q_score_alter_quiz_q_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='q_score',
            field=models.IntegerField(default='Null'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q_time',
            field=models.CharField(default='NUll', max_length=100),
        ),
    ]
