# Generated by Django 4.1b1 on 2023-03-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0008_remove_quiz_q_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quiz',
        ),
    ]
