# Generated by Django 4.1b1 on 2023-03-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0011_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='00-00-0000', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
