# Generated by Django 4.1b1 on 2023-03-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0012_user_college_user_dob_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='null', max_length=1000)),
            ],
        ),
    ]
