# Generated by Django 4.1b1 on 2023-03-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginn', '0015_js'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='user_id',
            field=models.IntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='java',
            name='user_id',
            field=models.IntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='js',
            name='user_id',
            field=models.IntegerField(default='null'),
        ),
    ]
